/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sfm_CONSTANTS_H
#define sfm_CONSTANTS_H

#include "sfm_types.h"

namespace vision { namespace sfm { namespace gen {

class sfmConstants {
 public:
  sfmConstants();

};

extern const sfmConstants g_sfm_constants;

}}} // namespace

#endif
