/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sfm_constants.h"

namespace vision { namespace sfm { namespace gen {

const sfmConstants g_sfm_constants;

sfmConstants::sfmConstants() {
}

}}} // namespace

